// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp9uWIyJgNS75CHYrzyANzHwK-QjN3G1E',
    appId: '1:873169823762:web:6ff765f7af0bf6f62150cb',
    messagingSenderId: '873169823762',
    projectId: 'calendarapp-33ea2',
    authDomain: 'calendarapp-33ea2.firebaseapp.com',
    databaseURL:
        'https://calendarapp-33ea2-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'calendarapp-33ea2.appspot.com',
    measurementId: 'G-1THRDM8LWX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8HPBw5JD2bJjK2tuNaDlw6m1IgDuzA_E',
    appId: '1:873169823762:android:9eb157a40d2837362150cb',
    messagingSenderId: '873169823762',
    projectId: 'calendarapp-33ea2',
    databaseURL:
        'https://calendarapp-33ea2-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'calendarapp-33ea2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCn3yHpHrOcKKFgA3W3v6mV08jg_TtW00',
    appId: '1:873169823762:ios:680de89fc737248e2150cb',
    messagingSenderId: '873169823762',
    projectId: 'calendarapp-33ea2',
    databaseURL:
        'https://calendarapp-33ea2-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'calendarapp-33ea2.appspot.com',
    iosClientId:
        '873169823762-45lsno9dun8piruqbmhh95qg2bhqllv5.apps.googleusercontent.com',
    iosBundleId: 'com.example.task1',
  );
}
